# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Eka Putra
tagline:          Catatan Eka Putra
url:              http://eka-putra.github.io
paginate:         1
baseurl:          /
author:
  name:           Eka Putra
  url:            https://twitter.com/eka415
  email:          ekaputtra@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/eka-putra/eka-putra.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
